apiVersion: v1
kind: Service
metadata:
    name: "datapower"
spec:
    selector:
        app: "datapower"
    type: LoadBalancer
    ports:
        - protocol: "TCP"
          - port: 9090
          # targetPort: 9090
          type: NodePort
