apiVersion: v1
kind: Service
metadata:
    name: "datapower"
spec:
    selector:
        app: "datapower"
    type: LoadBalancer
    ports:
        - port: 9090
          name: web-mgmt
          protocol: TCP
          targetPort: 9090
        - port: 80
          name: mpgw
          protocol: TCP
          targetPort: 80
